# Generated by Django 5.2.17 on 2026-08-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='normalised query', max_length=255)),
                ('country_filter', models.CharField(blank=True, default='', help_text='country asked for, if any', max_length=2)),
                ('query', models.CharField(help_text='what was originally asked', max_length=255)),
                ('found', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('country', models.CharField(blank=True, default='', help_text='country resolved', max_length=2)),
                ('source', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'geocode_cache',
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='geocode_cac_latitud_33216b_idx')],
                'constraints': [models.UniqueConstraint(fields=('key', 'country_filter'), name='geocode_cache_key_country')],
            },
        ),
    ]
