# Generated by Django 5.2.17 on 2026-08-07 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('address', models.URLField(blank=True, default='', max_length=512)),
            ],
            options={
                'db_table': 'website',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, default='')),
                ('link', models.URLField(blank=True, default='', max_length=512)),
                ('image', models.URLField(blank=True, default='', max_length=512)),
                ('author', models.CharField(blank=True, default='', max_length=128)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('content_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='tech.website')),
            ],
            options={
                'db_table': 'article',
                'ordering': ['-time', '-added_at'],
                'indexes': [models.Index(fields=['-time'], name='article_time_e9b0df_idx'), models.Index(fields=['-added_at'], name='article_added_a_88d6e0_idx')],
            },
        ),
    ]
